language: php
php:
- 5.5
- 5.4
notifications:
  hipchat:
    rooms:
    - HIPAPI@1981369
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
env:
  global:
    secure: DZCDrmR4GIXh9mGiS3ZaPpiz/ELFQyVtkx8+LNvkCKD+ebJsGagvrltqxOM92Z80hUsYwAnIjn4Nn65qrQCJEl41q9tVxccoVdEwDcoOvxhOAu6xDXQTUV43d2VWsuDp6FTK0vTXlwC/N/Vqr7lXmor5ypCWS9Vxw1izhm1ugPNtznlVpjkErqX6lL1y8uPYD+zQgJM3MFR6snjQKWECzlkBmwh37VbEnhkjSMxg8fy1bLukOa5RUceDjkOFPb1XSMabS23LvIgcV1vG6vBndxuPDIvEmm24r/UliC280l5ffbEcG9fDitqMOposvW6lP9//RZUAvIATPcykU7QaNB0/Mvps6gEtoHTdpbi5O9LdyAhIPC2kfl1RTZQlE28BSXxqubgwziRP07bKGBLTdaYqvFcwnswNMTwMeoS6dfCbmW4sCrb2d8CD7HSSB92kHtr+Sslfpkwow82UKzc0LHg2Cj4ctSuYOBnCKO5l5PsgoPpVE7WCbgn0oewb5jSezbZoD/5DHuMdBKJ9o8KzAXR0/0mbGHmr/klmwo8ToLp53kKtR0zU/oul+U5PcVw8rSFJAN2I//L9WrviiiyBdYkqMeuq/Z6s+SUaOCs5GlkYPLDB73iTdT67DCwnd0VjRWpN9jO5uH8HqHEVyi2rQuE4qe8ax6bSCUAxt9bX1YI=
