language: php
php:
- 5.5
- 5.4
notifications:
  hipchat:
    rooms:
      secure: vn1wYU/pazgQ9Cc1DSnTHC4TX05xYTBFylalOI5OoWhEJVVJBHQzKwa7uDboCsCgnrmVYQDJ4hglf7hjKMfbzZtC6KIGmCfDXpKX43tlqpU0GFKvY4BIHf5WRX8RzqYoUlDIgEmzJL+PUTennncYbmZsukQfw3OyZBHk7ScOCAASoeZIxugLB+an+sYG7QXtHZxtM2+VuZiTfebCfvOFV7ndnzQSIpy9bNwXYSeZDugpA+DO+Zf8zsUZeJvGcKTugikabKorRiN5YrMuxScSGvOHIRWoNVVJPb++wthUgqEeYBuwO0ji+wlKovBW0AlVIvoq1w522UWr8o7tPN1WonLjT/BIDEAr9s/AyUSywKfG6mXossskK8sQ0eyWu9NTcjXAqR1wrPgIzvrhrp5TlgGtu3YahwjS+ZUPmK4ek8WBGOng/ODi/1bIc/WTpwP8o0YFITkDcliFwYQdQpdibo32dQRjQZQujoc3mxKOtLvVnVYY2Qwpp1VGktb9kpxy4d2L8hFxrtlB7Jcz+cg3wJ0MGSb9yjmxREn5DXfFJKuAq19wTzbmvFClacIqyz4vLNG/Yll0T5K5WoZHDG9mRdFI3AHYmP216Y/W9obaYFK70WOnpqZtEUCPgFqV7MzRVS1lAvH4YaLd0f+KktP5QGn250h/EF37lAUPUBYD45c=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
